# Active Profile Default (Points to MS SQL Server for production/local runtime)
spring.profiles.active=prod

server.address=0.0.0.0
server.port=8000

# Common App Settings
spring.application.name=WordSanitizerApi
spring.jpa.show-sql=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000
